library(readr)
library(ggplot2)
analysis <- read_csv("roster-salary-stats.csv",col_names=TRUE)
sink("../../data/cleandata/eda-output.txt")
summary(analysis$salary)
sd(analysis$salary)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$salary)) + 
  geom_boxplot()
ggsave("../../images/salaries.png")
ggplot(data=analysis, aes(analysis$salary)) + 
       geom_histogram()
ggsave("../../images/salaries1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$height)
sd(analysis$height)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$height)) + 
  geom_boxplot()
ggsave("../../images/height.png")
ggplot(data=analysis, aes(analysis$height)) + 
       geom_histogram()
ggsave("../../images/height1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$weight)
sd(analysis$weight)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$weight)) + 
  geom_boxplot()
ggsave("../../images/weight.png")
ggplot(data=analysis, aes(analysis$weight)) + 
      geom_histogram()
ggsave("../../images/weight1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$G)
sd(analysis$G)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$G)) + 
  geom_boxplot()
ggsave("../../images/G.png")
ggplot(data=analysis, aes(analysis$G)) + 
       geom_histogram()
ggsave("../../images/G1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$FG)
sd(analysis$FG)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$FG)) + 
  geom_boxplot()
ggsave("../../images/FG.png")
ggplot(data=analysis, aes(analysis$FG)) + 
      geom_histogram()
ggsave("../../images/FG1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$FGA)
sd(analysis$FGA)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$FGA)) + 
  geom_boxplot()
ggsave("../../images/FGA.png")
ggplot(data=analysis, aes(analysis$FGA)) + 
       geom_histogram()
ggsave("../../images/FGA1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$FT)
sd(analysis$FT)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$FT)) + 
  geom_boxplot()
ggsave("../../images/FT.png")
ggplot(data=analysis, aes(analysis$FT)) + 
       geom_histogram()
ggsave("../../images/FT1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$FTA)
sd(analysis$FTA)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$FTA)) + 
  geom_boxplot()
ggsave("../../images/FTA.png")
ggplot(data=analysis, aes(analysis$FTA)) + 
       geom_histogram()
ggsave("../../images/FTA1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$TRB)
sd(analysis$TRB)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$TRB)) + 
  geom_boxplot()
ggsave("../../images/TRB.png")
ggplot(data=analysis, aes(analysis$TRB)) + 
       geom_histogram()
ggsave("../../images/TRB1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$AST)
sd(analysis$AST)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$AST)) + 
  geom_boxplot()
ggsave("../../images/AST.png")
ggplot(data=analysis, aes(analysis$AST)) + 
       geom_histogram()
ggsave("../../images/AST1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$STL)
sd(analysis$STL)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$STL)) + 
  geom_boxplot()
ggsave("../../images/STL.png")
ggplot(data=analysis, aes(analysis$STL)) + 
       geom_histogram()
ggsave("../../images/STL1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$BLK)
sd(analysis$BLK)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$BLK)) + 
  geom_boxplot()
ggsave("../../images/BLK.png")
ggplot(data=analysis, aes(analysis$BLK)) + 
       geom_histogram()
ggsave("../../images/BLK1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$TOV)
sd(analysis$TOV)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$TOV)) + 
  geom_boxplot()
ggsave("../../images/TOV.png")
ggplot(data=analysis, aes(analysis$TOV)) + 
       geom_histogram()
ggsave("../../images/TOV1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$PF)
sd(analysis$PF)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$PF)) + 
  geom_boxplot()
ggsave("../../images/PF.png")
ggplot(data=analysis, aes(analysis$PF)) + 
       geom_histogram()
ggsave("../../images/PF1.png")
sink("../../data/cleandata/eda-output.txt")
summary(analysis$PTS)
sd(analysis$PTS)
sink()
ggplot(analysis, aes(x=analysis$X1, y=analysis$PTS)) + 
  geom_boxplot()
ggsave("../../images/PTS.png")
ggplot(data=analysis, aes(analysis$PTS)) + 
       geom_histogram()
ggsave("../../images/PTS1.png")
sink("../../data/cleandata/eda-output.txt")
summary(factor(analysis$Team))
sink()
ggplot(analysis, aes(x=analysis$Team)) + 
  geom_bar()
ggsave("../../images/Team.png")
sink("../../data/cleandata/eda-output.txt")
summary(factor(analysis$position))
sink()
ggplot(analysis, aes(x=analysis$position)) + 
  geom_bar()
ggsave("../../images/position.png")